Update rhel-7-8-9-ad-domain-join-playbook-v2.yml

diff --git a/rhel-7-8-9-ad-domain-join-playbook-v2.yml b/rhel-7-8-9-ad-domain-join-playbook-v2.yml
--- a/rhel-7-8-9-ad-domain-join-playbook-v2.yml
+++ b/rhel-7-8-9-ad-domain-join-playbook-v2.yml
@@ -1,9 +1,9 @@
 ---
-- name: Detect and Execute RHEL 7, 8 & 9 OS-specific tasks
-  hosts: "{{ host_list }}"
+- name: Detect and Execute RHEL 789 OS-specific tasks
+  hosts: all
   gather_facts: yes
   vars:
-    domain_name: isddc.men.maxis.com.my
+    domain_name: wikilab.asia
     username: "{{ username }}"
     password: "{{ pass }}"
     domain_check_results: []
@@ -113,8 +113,17 @@
       when: not already_joined
     
     # Join domain section - only runs if server is not already joined
-    - name: Install packages for domain join
-      package:
+    - name: Install realm package
+      shell: |
+            if ! rpm -q realmd; then
+            yum install -y realmd || echo "Error: No package realmd available"
+            fi
+      register: check_realmpkg
+      failed_when: "'Error: No package realmd available' in check_realmpkg.stdout"
+      when: not already_joined
+
+    - name: Install realm package along with sssd
+     package:
         name: "{{ item }}"
         state: latest
       with_items:
@@ -158,7 +167,7 @@
       lineinfile:
         path: /etc/openldap/ldap.conf
         insertafter: BOF
-        line: 'TLS_CACERT      /etc/openldap/certs/isddc.mem.maxis.com.my.pem'
+        line: 'TLS_CACERT      /etc/openldap/certs/wikilab-ca.cer'
         state: present
         backup: yes
       when: not already_joined
@@ -172,7 +181,7 @@
         
     - name: Copy LDAP CERT
       copy:
-        src: isddc.mem.maxis.com.my.pem
+        src: Wikilab-ca.cer
         dest: /etc/openldap/certs
         mode: "0655"
       when: not already_joined
@@ -223,7 +232,7 @@
       ignore_errors: yes
       no_log: true
       when: not already_joined
-      
+
     - name: Print full SSH test output
       debug:
         var: ssh_test_before
@@ -239,7 +248,6 @@
           Stdout: {{ ssh_test_before.stdout }}
           Stderr: {{ ssh_test_before.stderr }}
           Command: {{ ssh_test_before.cmd }}
-      no_log: true    
       when: not already_joined
           
     - name: Print SSH test result before blacklisting
@@ -290,8 +298,8 @@
           Stdout: {{ ssh_test_after.stdout }}
           Stderr: {{ ssh_test_after.stderr }}
           Command: {{ ssh_test_after.cmd }}
-      no_log: true    
       when: not already_joined
+      #no_log: true
 
     - name: Print result of SSH login test after blacklisting
       debug:
